// <auto-generated />
using System;
using Firearm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Firearm.Migrations
{
    [DbContext(typeof(FirearmDbContext))]
    partial class FirearmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Firearm.Controllers.Models.Civillian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CivillianId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcadamicStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("Kebele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MartialStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredBodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredBodyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodyResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeOfCapital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Civillians");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.Destroyed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DestroyedId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuthorizationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthorizedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDestroyed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DestructionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestructionRequestedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForDestruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destroyeds");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.Firearm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("firearmId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuthorizedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmReturnedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonToReturn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Firearms");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.FirearmHolders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DestroyedId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("firearmHolders");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.Hmts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("firearmId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("LevelOfService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicensedCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredBodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredBodyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodyResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kebele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registeredResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hmts");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.Iofc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iofcPendingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ComingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CountryOfResidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenceOfMedical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonHeCame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredBodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredBodyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodyResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kebele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registeredResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("iofcs");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.Loss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LossId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateLost")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Losses");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userFullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OfficerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredBodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredBodyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodyResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.OfficerPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OfficerPendingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredBodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredBodyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodyResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("officerPendings");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.Poag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("poagId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfOrganisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredBodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredBodyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodyResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeOfCapital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kebele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registeredResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sector")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Poages");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EFPID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Extension")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mobile")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nameid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.Withdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("withdrawId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WithdrawalDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("withdrawals");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.civillianPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CivillianPendingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcadamicStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("Kebele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MartialStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredBodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredBodyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodyResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeOfCapital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("civillianPendings");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.distructionPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("distructionPendingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuthorizationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthorizedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDestroyed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DestructionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestructionRequestedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForDestruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("distructionPendings");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.hmtsPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hmtsPendingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("LevelOfService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicensedCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredBodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredBodyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodyResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kebele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registeredResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hmtsPendings");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.iofcPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iofcPendingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ComingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CountryOfResidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenceOfMedical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonHeCame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredBodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredBodyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodyResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kebele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registeredResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("iofcPendings");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.lossPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lossPendingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateLost")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("losspendings");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.poagPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("poagOfficerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfOrganisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredBodyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredBodyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodyResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredBodySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeOfCapital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kebele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registeredResponsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sector")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("poagPendings");
                });

            modelBuilder.Entity("Firearm.Controllers.Models.recoverPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recoverPendingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuthorizedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateMarked")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirearmCalibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmReturnedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirearmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirearm")
                        .HasColumnType("bit");

                    b.Property<string>("MagazineCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonToReturn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearManufacture")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("recoverPendings");
                });
#pragma warning restore 612, 618
        }
    }
}
